EBC\AdvertiserClient\BidAdvisor\BidAdvisor:
    properties:
        currentReach:
            type: integer
        maximumReach:
            type: integer
        suggestedBid:
            type: float
        miBid:
            type: float
