EBC\AdvertiserClient\Campaign\SuppressionImport:
    properties:
        importDate:
            type: string
        name:
            type: string
        processedEmailAddresses:
            type: integer
        totalEmailAddresses:
            type: integer
        lastProcessedDate:
            type: string
