EBC\AdvertiserClient\Campaign\InvalidImportResponse:
    properties:
        totalEmails:
            type: integer
        totalInvalidEmails:
            type: integer
        invalidEmailsSample:
            type: array
