name: Advertiser Client
baseUrl: "{scheme}://{host}{+basePath}/{advertiserId}"
description: Advertiser Client
operations:
    getBidAdvisor:
        httpMethod: GET
        uri: bidadvisor
        responseClass: 'EBC\AdvertiserClient\BidAdvisor\BidAdvisor'
        summary: Return price points
        data:
            acceptedStatusCodes: 200
        parameters:
             country:
                location: query
                description: Country Id
                type: string
                required: true
             publishers:
                location: query
                description: Publisher Id
                type: string
                required: false
             lists:
                location: query
                description: Lists Id
                type: string
                required: false
             genders:
                location: query
                description: Genders Id
                type: string
                required: false
             ages:
                location: query
                description: Ages Id
                type: string
                required: false
             regions:
                location: query
                description: Regions Id
                type: string
                required: false
             zones:
                location: query
                description: Zones Id
                type: string
                required: false
             groups:
                location: query
                description: Groups Id
                type: string
                required: false
             category:
                location: query
                description: Category Id
                type: string
                required: true
             minBid:
                location: query
                description: MinBid Id
                type: string
                required: false
             campaign:
                location: query
                description: Campaign Id
                type: string
                required: true

    getCampaignSuppressionImports:
        httpMethod: GET
        uri: campaigns/{campaignId}/suppressions/imports
        responseClass: 'EBC\AdvertiserClient\Campaign\SuppressionImports'
        summary: Returns the suppression imports for the given campaign
        data:
            acceptedStatusCodes: 200
        parameters:
            campaignId:
                location: uri
                description: Id of the campaign to use
                type: integer
                required: true

    createCampaignSuppressionImport:
        httpMethod: POST
        uri: campaigns/{campaignId}/suppressions/imports
        responseClass: 'EBC\AdvertiserClient\Campaign\SuppressionImportResponse'
        summary: Save a campaign suppression import
        data:
            acceptedStatusCodes: 200
        parameters:
            campaignId:
                location: uri
                description: Id of the campaign to use
                type: integer
                required: true
            suppression_import:
                location: json
                description: The form of suppression
                type: object
                required: true
                properties:
                    source:
                        location: json
                        required: true
                        type: string
                    location:
                        location: json
                        required: false
                        type: string
                    data:
                        location: json
                        required: false
                        type: string
